[Athena]
openai_vector_store_id = 
elevenlabs_voice_id =

; Enable features by setting their value to either TRUE or FALSE.
feature_web_search = 
feature_file_search =
feature_reasoning =
feature_audio_tags =

[Poseidon]
openai_vector_store_id = 
elevenlabs_voice_id =

; Enable features by setting their value to either TRUE or FALSE.
feature_web_search =
feature_file_search =
feature_reasoning =
feature_audio_tags =