[Athena]
; Override the OpenAI Vector Store ID by entering your custom Vector Store ID. A Vector Store ID is needed if the file search feature is enabled.
openai_vector_store_id = 
; Override the ElevenLabs Voice ID by entering your custom Voice ID.
elevenlabs_voice_id =

; Override features by setting their value to either TRUE or FALSE.
feature_web_search = 
feature_file_search =
feature_reasoning =
feature_audio_tags =

[Poseidon]
; Override the OpenAI Vector Store ID by entering your custom Vector Store ID. A Vector Store ID is needed if the file search feature is enabled.
openai_vector_store_id = 
; Override the ElevenLabs Voice ID by entering your custom Voice ID.
elevenlabs_voice_id =

; Override features by setting their value to either TRUE or FALSE.
feature_web_search =
feature_file_search =
feature_reasoning =
feature_audio_tags =